config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
root 'books#index'

namespace :admin do
resources :authors, :books, :categories
end
resources :authors, :books, :categories
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
	has_many :books
end

app/models/book.rb
class Book < ApplicationRecord
  has_many :authors
  belongs_to :user
  has_many :categories
  has_many :images, :dependent => :destroy
  has_many :comments
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :books
end

app/models/comment.rb
class Comment < ApplicationRecord
	has_many :books
	
end

app/models/image.rb
class Image < ApplicationRecord
	belongs_to :book
	 # has_attached_file :picture, styles: { medium: "350x250>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  # 	validates_attachment_content_type :picture, content_type: /\Aimage\/.*\z/
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :comments
  has_many :books
  has_many :images
end

app/controllers/admin/authors_controller.rb
class Admin::AuthorsController < ApplicationController

	layout 'admin'
	
	def index
		@authors = Author.all
	end

	def new
		@author = Author.new
	end

	def create
		@author = Author.new(author_params)
		if @author.save
			redirect_to root_path
		else
			render 'new'
		end
	end

	private

	def author_params
		params.require(:author).permit(:name, :sur_name)
	end
end

app/controllers/admin/books_controller.rb
class Admin::BooksController < ApplicationController

	layout 'admin'
	def index
		@books = Book.all
	end

	def new
		@book = Book.new
	end

	def create
		@book = Book.new(book_params)
		if @book.save
			if params[:images]
				params[:images].each { |image|
					@author.pictures.create(image: picture)
				}
			end
			redirect_to root_path
		else
			render 'new'
		end

	end

	private
	def book_params
		params.require(:book).permit(:title, :author_id, :category_id, :desc, :image_id, :user_id)
	end
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < ApplicationController
	def index

	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
	def new
		@author = Author.new
	end

	def create
		@author = Author.new(author_params)
		if @author.save
			redirect_to root_path
		else
			render 'new'
		end
	end

	private

	def author_params
		params.require(:author).permit(:name, :sur_name)
	end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
	def index
		@books = Book.all
	end

	def new
		@book = Book.new
	end

	def create
		@book = Book.new(book_params)
		if @book.save
			redirect_to root_path
		else
			render 'new'
		end

	end

	private
	def book_params
		params.require(:book).permit(:title, :author_id, :category_id, :desc, :image_id, :user_id)
	end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
	def index

	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/admin/authors/_form.html.erb
<div class="wrapper">
  <%= simple_form_for @author do |f| %>
  <%= f.input :name %>
  <%= f.input :sur_name %>
  <%= f.submit 'Create new author', class: 'btn btn-primary' %>
<% end %>
</div>

app/views/admin/authors/index.html.erb
<table class="table">
  <thead>
    <tr>
      <th>#</th>
      <th>Name</th>
      <th>Surname</th>
    </tr>
  </thead>
  <tbody>
  <% @authors.each do |author| %>
    <tr>
      <th scope="row"><%= @authors.count%></th>
      <td><%= author.name %></td>
      <td><%= author.sur_name %></td>
    </tr>
    <% end %>

  </tbody>

</table>

app/views/admin/authors/new.html.erb
<%= render 'form.html.erb'%>

app/views/admin/books/_form.html.erb
<div class="wrapper">
  <%= simple_form_for @book do |f| %>
  <%= f.input :title %>
  <%= f.collection_select :author_id, Author.all, :id, :name, input_html: { class: 'select'} %><be/>
  <%= f.collection_select :category_id, Category.all, :id, :title %>
  <%= f.input :desc, as: :text %>
  <%= f.input :image_id, as: :file, multiple: true %>
  <%= f.hidden_field :user_id, value: current_user.id %>
  <%= check_box_tag 'I understand', id: 'check'%>
  <%= f.submit 'Create new book', class: 'btn btn-primary', id: 'confirm' %>
<% end %>
</div>

<script>
  $('#check').click(function() {
        if ($(this).is(':checked')) {
            $('#confirm').attr('disabled', 'disabled');
        } else {
            $('#confirm').removeAttr('disabled');
        }
    });
</script>

app/views/admin/books/edit.html.erb
<%= render 'form.html.erb' %>

app/views/admin/books/new.html.erb
<%= render 'form.html.erb' %>

app/views/admin/categories/index.html.erb
<p>hello</p>

app/views/books/_form.html.erb
<div class="wrapper">
  <%= simple_form_for @book do |f| %>
  <%= f.input :title %>
  <%= f.collection_select :author_id, Author.all, :id, :name, input_html: { class: 'select'} %><be/>
  <%= f.collection_select :category_id, Category.all, :id, :title %>
  <%= f.input :desc, as: :text %>
  <%= f.input :image_id, as: :file %>
  <%= f.hidden_field :user_id, value: current_user.id %>
  <%= f.submit 'Create new book', class: 'btn btn-primary' %>
<% end %>
</div>

app/views/books/index.html.erb
<div class="container">
  <div class="row">
    <div class="well">
      <h1>All books</h1>
      <p>Select category all</p>
      <% @books.each do |book|%>
      <div class="list-group">
        <a href="book" class="list-group-item">
          <div class="media col-md-3">
            <figure class="pull-left">
              <img class="media-object img-rounded img-responsive"  src="http://placehold.it/350x250" alt="placehold.it/350x250" >
            </figure>
          </div>
          <div class="col-md-6">
          <h4 class="list-group-item-heading"><%= book.title %></h4>
            <p class="list-group-item-text">
            <%= book.desc%>
            </p>
            <em><p><%= book.authors.name %></p></em>
          </div>
        </a>
      </div>
      <% end %>

      <div class="list-group">
        <a href="#" class="list-group-item">
          <div class="media col-md-3">
            <figure class="pull-left">
              <%= image_tag("/images/index.jpeg", size:"350x250", class: "media-object img-rounded img-responsive") %>
              <!-- <img class="media-object img-rounded img-responsive"  src="http://placehold.it/350x250" alt="placehold.it/350x250" > -->
            </figure>
          </div>
          <div class="col-md-6">
            <h4 class="list-group-item-heading"> Object oriented </h4>
            <p class="list-group-item-text"> Qui diam libris ei, vidisse incorrupte at mel. His euismod salutandi dissentiunt eu. Habeo offendit ea mea. Nostro blandit sea ea, viris timeam molestiae an has. At nisl platonem eum. 
              Vel et nonumy gubergren, ad has tota facilis probatus. Ea legere legimus tibique cum, sale tantas vim ea, eu vivendo expetendis vim. Voluptua vituperatoribus et mel, ius no elitr deserunt mediocrem. Mea facilisi torquatos ad.
            </p>
          </div>
        </a>
      </div>
    </div>
  </div>


</div>
</div>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FinalKont</title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
  <nav class="navbar navbar-default">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to 'Library(Admin)', books_path, class: 'navbar-brand' %>
        <!-- <a class="navbar-brand" href="#">Library</a> -->
      </div>
      <div class="categories">
        <li><%= link_to 'Book', admin_books_path ,class: 'btn btn-primary' %></li>
        <li><%= link_to 'Author', admin_authors_path,class: 'btn btn-primary' %></li>
        <li><%= link_to 'Categories', admin_categories_path,class: 'btn btn-primary' %></li>
      </div>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
  <%= yield %>
</body>

<style>
  .categories {
    margin-left: 35em;
    margin-top: 5px;
  }

  .categories li {
    display: inline;
    padding-right: 15px;
  }
</style>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FinalKont</title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
  <nav class="navbar navbar-default">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to 'Library', books_path, class: 'navbar-brand' %>
        <!-- <a class="navbar-brand" href="#">Library</a> -->
      </div>
      <% if user_signed_in? %>
      <form class="navbar-form navbar-left form-margin">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <!-- Изменить на руби таг -->
        <button type="submit" class="btn btn-success">Submit</button>
      </form>
      <% end %>
      <% unless user_signed_in? %>
      <ul class="nav navbar-nav navbar-right"> 
        <%= link_to 'Sign Up', new_user_registration_path, class: 'btn btn-primary devise-button' %>
        <%= link_to 'Login', new_user_session_path, class: 'btn btn-primary devise-button right' %>
        <% else %>
        <div class="user-nav">
        <p>Hello <%= current_user.email %></p>
        <%= link_to 'Add new book', new_book_path %> |
        <%= link_to 'Add new author', new_author_path %>
        </div>
      </ul>
      <% end %>
      
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
<%= yield %>
</body>
</html>